language: node_js
sudo: required
dist: trusty
node_js:
  - '8.9.1'

addons:
  chrome: stable


branches:
  except:
    - TestRelease

cache:
  directories:
     - ./node_modules

before_script:
   - "sudo chown root /opt/google/chrome/chrome-sandbox"
   - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

script:
  - ./scripts/ci/build.sh prod
  - ./scripts/ci/build.sh ci
  - ./scripts/ci/lint.sh ci
  - ./scripts/ci/test.sh ci



notifications:
  email:
    on_failure: change
    on_success: change



after_success:
  - echo "Build ok"

after_failure:
    - echo "Build KO"

